services:
  db:
    image: postgres:16
    container_name: eda2da_db
    environment:
      POSTGRES_DB: eda2da_db
      POSTGRES_USER: eda2da_user
      POSTGRES_PASSWORD: eda2da_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: eda2da_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: