# Generated by Django 5.0.4 on 2026-04-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_allergen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Легко'), ('Medium', 'Средне'), ('Hard', 'Сложно')], default='Easy', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_moderated',
            field=models.BooleanField(default=False),
        ),
    ]
